puzzlepiece:
  slug: "puzzlepiece"
  name: "Puzzle Piece"
  prefix: "pp"
  disorder: "Autism"
  email: "hello@trypuzzlepiece.com"
  base_url: "https://www.trypuzzlepiece.com"
  apps_url: "https://www.amazon.com/gp/product/B07B3JW5HN"
helpinghands:
  slug: "helpinghands"
  name: "Helping Hands"
  prefix: "hh"
  disorder: "Down Syndrome"
  email: "hello@buyhelpinghands.com"
  base_url: "https://www.gethelpinghands.com"
  apps_url: "https://www.amazon.com/gp/product/B07B9JR3JY"
focusfinder:
  slug: "focusfinder"
  name: "Focus Finder"
  prefix: "ff"
  disorder: "ADHD"
  email: "hello@getfocusfinder.com"
  base_url: "https://www.getfocusfinder.com"
  apps_url: "https://www.amazon.com/gp/product/B07B3JW5HN"
